---
title: "Does non-stationary spatial data always require non-stationary random fields?"
author: "Adrien Allorant and Austin Carter"
date: "3/10/2020"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Summary

**Real world processes have spatially varying second-order structure, but is modeling this non-stationarity worth it?**

The authors develop a novel model for non-stationary covariance structure and illustrate methods for parameterizing the model. They then apply their model to US precipitation data and compare predictions from their stationary and non-stationary models. They conclude by recommending careful consideration of the sources of non-stationarity and encourage balance between fitting complicated/flexible models and fitting simple/smarter models.

## Classical Approaches to Non-stationarity and Anisotropy

Anisotropy = Not Isotropic

$\rho(h) = \rho(\tilde h)$ implies that $h = \tilde h$. This is not true in the case of anisotropy.

Non-stationarity in the covariance structure

* Global Deformation 
    - Pre-compute a transformation of distance and then use a stationary model

$\rho(\tilde h) = \rho(L_1||\vec s_2 - \vec s_1||)$

* Local Deformation via SPDE


## Stationary SPDE

The following equation defines a stochastic partial differential equation (SPDE), $u(\vec s)$, whose solution is the Matérn covariance function

$$
\begin{aligned}
(\kappa ^2 - \nabla \cdot \nabla) u(\vec s) = \sigma \mathcal{W}(\vec s),\qquad \vec s \in \mathbb{R}^2
\end{aligned}
$$

Where $\kappa$ and $\sigma > 0$ are constants, $\nabla = \left(\frac{\partial}{\partial x}, \frac{\partial}{\partial y}\right)^T$ and $\cal W$ is a standard Gaussian white noise process. This correlation structure is isotropic because the Laplacian, $\Delta = \nabla \cdot \nabla$ is equal to the sum of the diagonal elements of the Hessian, is invariant to a change of coordinates that involves rotation and translation. The solution to this SPDE is a class of equations that have covariance described by the Matérn covariance function.

## GMRF Approximation

Insert picture of GMRF approximation

## Model for Non-stationarity

The authors introduce a $2 \times 2$ matrix $\mathbf{H}$ into the SPDE which acts as a transformation of the grid on top of which we are measuring distance
$$
\begin{aligned}
(\kappa ^2 - \nabla \cdot \mathbf{H} \nabla) u(\vec s) &= \sigma \mathcal{W}(\vec s),\qquad \vec s \in \mathbb{R}^2 
\end{aligned}
$$
This results in an updated covariance function
$$
\begin{aligned}
r(\vec s_1, \vec s_2) &= \frac{\sigma ^2}{4 \pi \kappa^2\sqrt{\det(\mathbf{H})}}\left(\kappa||\mathbf{H}^{-1/2}(\vec s_2 - \vec s_1) || \right) K_1 \left(\kappa||\mathbf{H}^{-1/2}(\vec s_2 - \vec s_1) || \right) 
\end{aligned}
$$

Parameters $\kappa$ and $\mathbf{H}$ control the marginal variance and directionality of correlation, allowing $\sigma$ to fall out of the SPDE formmula. The $\sqrt{\det(\mathbf{H})}$ that appears in the denominator of the covariance function is a consequence of the change of variable.


## 2D-Random Walk Penalty

To enforce smoothness of parameters across space, the authors introduce a second-order penalty into their model for spatially-specific covariance parameters:

$$ - \Delta \beta(\vec s) = \cal W_{\beta}(\vec s) / \sqrt{\tau_{\beta}} $$

where $\beta(\vec s)$ is the location-specific value for parameter $\beta$ and

$$ \log(\beta(\vec s)) = \sum_{i = 1}^k\sum_{j = 1}^l \alpha_{ij}f_{ij}(\vec s)$$

where $\{\alpha_{ij}\}$ are the parameters for real-valued basis functions $\{f_{ij}\}$.

$$ \vec \alpha \sim \cal N_{kl}\left(\vec 0, \mathbf{Q}_{\textrm{RW2}}^{-1} / \tau_{\beta}\right) $$

## Full Hierachical Model


## Stationary vs. Non-stationary Model Predictions (Authors)

Insert plots

## Stationary vs. Non-stationary Model Predictions (Re-implementation)
